Task2
YosaRem/Robots pull request #2
Opened 2020-04-26 04:21 UTC by YosaRem

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
> +    public final String windowName = "GameWindow";
`static`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
> +        final WindowPosition position = new WindowPosition(
лишняя переменная, можно сразу делать `return new WindowPosition(...)`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
> +        Restorer.restoreInternalFrame(this, store.getOrDefault(windowName, defaultPosition));
не вижу смысла в классе `Restorer` т.к. у него только один метод и он используется здесь. предлагаю просто сделать приватным методом в `GameWindow` по аналогии с `LogWindow`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private final String windowName = "mainWindow";
нигде не используется

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/store/WindowPosition.java
> +    private int Y;
поля могут быть `final`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/store/WindowPosition.java
> +    private int Y;
давай еще `x` и `y` в нижнем регистре. будем соблюдать `Java Naming Convention`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/store/Restorer.java
> +public class Restorer {
выше писал почему этот класс не нужен

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/store/PositionStore.java
> +    private Map<String, WindowPosition> data;
Поля могут быть `final` и давай перенесем инициализацию `toStore` в конструктор для единообразия

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    private final PositionStore store = new PositionStore(System.getProperty("user.home"));
Неправильно, что `JFrame` знает о каком=то механизме сохранения/восстановления состояния. Предлагаю в `MainApplicationFrame` сделать методы `restore`/`store` как в `GameWindow` и `LogWindow`. Чтобы извне они вызывались. При вызове `store` у `MainApplicationFrame` будет возвращаться объект, который будет содержать в себе состояние `GameWindow` и `LogWindow`, а что с этим объектом будет происходить после уже не обязанность `JFrame`

2020-04-26 15:39 UTC, shaykemelov commented on robots/src/store/Restorable.java
> +public interface Restorable {
мне кажется два интерфейса излишне, можно обойтись одним `Storable`, в котором будут оба метода `restoreOrDefault` и `getDataForStore`

2020-04-27 05:03 UTC, YosaRem commented on robots/src/gui/GameWindow.java
> +        Restorer.restoreInternalFrame(this, store.getOrDefault(windowName, defaultPosition));
Если не выносить этот код в отдельный класс, то для каждого JInternalFrame нужно будет писать свою функцию restore. Учитывая, что дальше нужно будет ещё добавить фреймов, кажется, что такой класс вполне уместен.

2020-04-27 05:46 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
> +        Restorer.restoreInternalFrame(this, store.getOrDefault(windowName, defaultPosition));
Преждевременная оптимизация и всякие заготовки на будущее очень часто так и остаются не нужными. Ты ведь не знаешь к тому времени будут ли все фреймов одинаково восстанавливаться, возможно придётся какой-либо паттерн применить, а на данный момент это неизвестно. А новый класс всегда можно написать, когда в нем действительно будет необходимость, сейчас ее нет

2020-04-27 06:18 UTC, YosaRem commented on robots/src/store/PositionStore.java
> +    private Map<String, WindowPosition> data;
Исправил.

2020-04-27 06:18 UTC, YosaRem commented on robots/src/gui/GameWindow.java
> +    public final String windowName = "GameWindow";
Исправил.

2020-04-27 06:18 UTC, YosaRem commented on robots/src/gui/LogWindow.java
> +        final WindowPosition position = new WindowPosition(
Исправил.

2020-04-27 06:18 UTC, YosaRem commented on robots/src/gui/MainApplicationFrame.java
> +    private final String windowName = "mainWindow";
Исправил.

2020-04-27 06:18 UTC, YosaRem commented on robots/src/store/WindowPosition.java
> +    private int Y;
Исправил.

2020-04-27 06:19 UTC, YosaRem commented on robots/src/gui/MainApplicationFrame.java
> +    private final PositionStore store = new PositionStore(System.getProperty("user.home"));
Вроде, поправил.

2020-04-27 06:19 UTC, YosaRem commented on robots/src/store/Restorable.java
> +public interface Restorable {
Исправил.

2020-04-27 06:19 UTC, YosaRem commented
@shaykemelov

2020-04-27 20:07 UTC, shaykemelov requested changes
tofix

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
> +    public static final String windowName = "GameWindow";
константы в `Java` принято писать в верхнем регистре `WINDOW_NAME`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
> +    public static String windowName = "LogWindow";
может быть `final` и `WINDOW_NAME`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
> +        this.setVisible(true);
по-моему метод избыточен, его содержимое можно перенести в `public void restore(Map<String, WindowPosition> store)`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/store/WindowPosition.java
> +public class WindowPosition {
по-моему `WindowState` больше подходит как имя класса

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/store/Restorer.java
> +public class Restorer {
все еще считаю, что класс не нужен

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/store/Storable.java
> +}
Раз уж у нас `WindowPosition` сменится на `WindowState`, предлагаю переименовать интерфейс в `HasState`, а методы в `getState` и `setState`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +                        PositionStore store = new PositionStore(frame, System.getProperty("user.home"));
можно избавиться от переменной `frame`, вместо этого передавать `MainApplicationFrame.this`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/store/PositionStore.java
> +    }
предлагаю использовать `try-with-resources`

2020-04-27 20:07 UTC, shaykemelov commented on robots/src/store/PositionStore.java
> +    }
предлагаю использовать `try-with-resources`

2020-04-28 03:21 UTC, YosaRem commented on robots/src/store/PositionStore.java
> +    }
Исправил.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/store/PositionStore.java
> +    }
Исправил.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/gui/MainApplicationFrame.java
> +                        PositionStore store = new PositionStore(frame, System.getProperty("user.home"));
Исправил.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/store/Storable.java
> +}
Переименовал.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/store/WindowPosition.java
> +public class WindowPosition {
Переименовал.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/gui/LogWindow.java
> +        this.setVisible(true);
Исправил.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/gui/LogWindow.java
> +    public static String windowName = "LogWindow";
Fixed.

2020-04-28 03:21 UTC, YosaRem commented on robots/src/gui/GameWindow.java
> +    public static final String windowName = "GameWindow";
Исправил.

2020-04-28 03:22 UTC, YosaRem commented
@shaykemelov

2020-04-28 06:47 UTC, merged

2020-04-28 06:50 UTC, shaykemelov reviewed
lgtm