Task3
YosaRem/Robots pull request #3
Opened 2020-05-04 20:03 UTC by YosaRem

Разделил логику движения и отображения робота. 
Добавил окно, в котором выводится информация о местоположении робота.

2020-05-16 11:29 UTC, shaykemelov requested changes
робот не может найти точку, если поставить ее рядом с ним изначально. в итоге он просто двигается по кругу.

tofix

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/gui/GameVisualizer.java
> +    protected void onRedrawEvent() {
метод может быть `private`

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/gui/GameVisualizer.java
> +    private void drawTarget(Graphics2D g, int x, int y) {
метод может быть `static`

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
>      public static final String WINDOW_NAME = "GameWindow";
константа можеть быть `private`

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/gui/RobotInfoWindow.java
> +        }
дублирующийся код, полагаю теперь можно вынести в общее место
`gui.GameWindow#setState`
`gui.RobotInfoWindow#setState`

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/gui/RobotInfoWindow.java
> +    private static final JTextField infoField = new JTextField();
предлагаю не делать текстовое поле константой, а унести инициализацию в конструктор.

2020-05-16 11:29 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +    private final List<Observer> observers = new ArrayList<>();
давай инициализацию в конструктор унесем

2020-05-16 16:37 UTC, YosaRem commented on robots/src/robot/Robot.java
> +    private final List<Observer> observers = new ArrayList<>();
Я вынесу в конструктор, но почему плохо так инициализацию проводить? 
Просто у меня IDEA ругается, что эта штука может быть не инициализированна, если инициализацию проводить в конструкторе.

2020-05-16 18:02 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +    private final List<Observer> observers = new ArrayList<>();
> почему плохо так инициализацию проводить?
это не плохо. это для единообразия т.к. остальные поля инициализируются в конструкторе.

у меня IDEA не ругается

```
    ...
    private final List<Observer> observers;
    ...
    public Robot(double robotPositionX, double robotPositionY, Target target) {
        this.observers = new ArrayList<>();
        this.robotPositionX = robotPositionX;
        this.robotPositionY = robotPositionY;
        this.target = target;
        robotDirection = 1;
    }
```

2020-05-17 01:36 UTC, YosaRem commented
@shaykemelov

2020-05-17 09:43 UTC, shaykemelov requested changes
если приложение запускается в первый раз, то по умолчанию окна расположены в левом верхнем углу и перекрывают друг-друга, к тому же игровое поле сжато до минимума.

 tofix

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/RobotInfoWindow.java
> +    private static JTextField infoField;
поле не должно быть `static`. т.к. оно у тебя станет одно на все объекты класса. замени `static` на `final`

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/RobotInfoWindow.java
> +import java.beans.PropertyVetoException;
неиспользуемый импорт

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
>  import java.beans.PropertyVetoException;
неиспользуемый импорт

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/GameWindow.java
> +
лишняя пустая строка

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected LogWindow createLogWindow() {
`private static`

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/gui/MainApplicationFrame.java
> +    protected void addWindow(JInternalFrame frame) {
`private`

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +import log.Logger;
неиспользуемый импорт

2020-05-17 09:43 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +import java.awt.geom.Point2D;
неиспользуемый импорт

2020-05-17 10:23 UTC, YosaRem commented
@shaykemelov

2020-05-17 10:25 UTC, shaykemelov approved these changes
lgtm

2020-05-17 10:25 UTC, merged