Task4
YosaRem/Robots pull request #4
Opened 2020-05-21 02:36 UTC by YosaRem

2020-05-23 17:48 UTC, shaykemelov requested changes
tofix

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
>      private TextArea m_logContent;
`final`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
>      public static final String WINDOW_NAME = "LogWindow";
`private`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +    }
предлагаю реализацию для `observers` заменить на `CopyOnWriteArrayList`, тогда в методах `registerObserver` и `unregisterObserver` можно будет убрать `synchronized`

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/Logger.java
>      }
здесь статический блок не нужен. можно сразу инциализировать `defaultLogSource`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
>  import java.util.Collections;
неиспользуемый импорт

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +        listeners = new ArrayList<>();
предлагаю реализацию для `listeners` заменить на `CopyOnWriteArrayList`, тогда в методах `registerObserver` и `unregisterObserver` можно будет убрать `synchronized`

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LogWindowSource.java
> +    private final ArrayList<Observer> listeners;
1. `ArrayList` -> `List`
2. `listeners` -> `observers`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LimitedList.java
> +    public LimitedList(int limit) {
если передать отрицательное число, то все сломается. можно выбрасывать `IllegalArgumentException` с пояснением, что `limit` не может быть отрицательным

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LimitedList.java
> +    private final int LIMIT;
почему `LIMIT` в в верхнем регистре? это ведь не константа

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LimitedList.java
> +    synchronized public void add(T element) {
пожалуйста поменяй порядок модификаторов

с `synchronized public` на `public synchronized`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LimitedList.java
> +        }
получается, что никакого вытеснения на самом деле нет. в памяти будут хранится все элементы до тех пор, пока `start` не достигнет `Integer.MAX_VALUE - LIMIT`

это неэффективное использование памяти, приложение быстрее упадет с `OutOfMemoryError`, прежде чем мы хоть раз зайдем в `toStart()`

2020-05-23 17:48 UTC, shaykemelov commented on robots/src/log/LimitedList.java
> +        }
по заданию: старые записи должны вытесняться

2020-05-29 15:37 UTC, YosaRem commented
@shaykemelov

2020-06-02 23:52 UTC, shaykemelov requested changes
tofix

2020-06-02 23:52 UTC, shaykemelov commented on robots/src/robot/Robot.java
> +    }
что-то не увидел этого исправления

2020-06-02 23:52 UTC, shaykemelov commented on robots/src/log/Logger.java
> +    private static final LogWindowSource defaultLogSource = new LogWindowSource(10);
константам в `Java` принято давать имена в таком формате `DEFAULT_LOG_SOURCE`

2020-06-02 23:52 UTC, shaykemelov commented on robots/src/gui/LogWindow.java
>      private LogWindowSource m_logSource;
тож `final`

2020-06-03 01:51 UTC, YosaRem commented
@shaykemelov

2020-06-07 16:16 UTC, shaykemelov approved these changes
lgtm

2020-06-07 16:16 UTC, merged